baseURL: https://koudijs.dev/
languageCode: en-us
title: koudijs.dev
paginate: 5

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: ExampleSite
  description: "ExampleSite description"
  keywords: [Blog, Portfolio, PaperMod]
  author: Simon Koudijs
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  # search https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 800
    threshold: 0.6
    minMatchCharLength: 3
    keys: ["title", "permalink", "summary", "content"]

  profileMode:
    enabled: true
    subtitle: "Welcome to my blog"
    imageUrl: "images/simon.jpg"
    imageTitle: "Some guy"
    imageWidth: 220
    imageHeight: 220
    buttons:
    - name: Posts
      url: "/posts"
    - name: Github
      url: "https://github.com/sunib"

outputs:
  home:
  - HTML
  - RSS
  - JSON

menu:
  main:
    - name: posts
      url: posts
      weight: 10
    - name: about
      url: about
      weight: 10
    - name: search
      url: search/
      weight: 10
    - identifier: tags
      name: tags
      url: tags
      weight: 20

taxonomies:
   tag: tags
   series: series
