baseURL: https://koudijs.dev/
#languageCode: en-us
title: koudijs.dev
paginate: 5

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: ExampleSite
  description: "ExampleSite description"
  keywords: [Blog, Portfolio, PaperMod]
  author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  profileMode:
    enabled: true
    title: "<Title>" # optional default will be site title
    subtitle: "Welkom op mijn website"
    imageUrl: "images/simon.jpg"
    imageTitle: "<title of image as alt>" # optional
    imageWidth: 220 # custom size
    imageHeight: 220 # custom size
    buttons:
    - name: Posts
      url: "/posts"
    - name: Github
      url: "https://github.com/sunib"

menu:
  main:
    - name: posts
      url: posts
      weight: 10
    - name: about
      url: about
      weight: 10
    - identifier: tags
      name: tags
      url: tags
      weight: 20

taxonomies:
   tag: tags
   series: series
